# Generated by Django 3.2.3 on 2025-10-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_editrequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_input', models.TextField(verbose_name='用户输入')),
                ('model_output', models.TextField(blank=True, null=True, verbose_name='模型输出')),
                ('status', models.CharField(default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '聊天日志',
                'verbose_name_plural': '聊天日志',
            },
        ),
    ]
