# Generated by Django 3.2.3 on 2025-10-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chatlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatLog',
        ),
    ]
